### ISSUE TITLE
Realizar mockups

### ISSUE THREAD

**Issue by JoelMendoza1** [ANP-2020A/proyecto-semestre-sistema-para-practicas-preprofesionales#3]
- Página Inicial
- Página Iniciar Sesión
- Página Registrar Usuario (Postulante y Empresa)
- Página sesión de Postulante
- Página sesion de Empresa

**Comment by Gabiita** [comment]
https://ninjamock.com/Designer/Workplace/129875496/CreacinOferta
https://ninjamock.com/Designer/Workplace/129827069/InicioEmpresa
